### ISSUE TITLE
Missing repos from users with a lot of repos.

### ISSUE THREAD

**Issue by tellnes** [Me1000/issues#215]
If you try to add a repo from eg. SubStack, then you are missing most of the repos. This makes it impossible to add those missing repos.

**Comment by Me1000** [comment]
Interesting, probably because you have more than 100 repos and GitHub paginates results after 100. I'll get this fixed in a future update, thanks for reporting this!

**Comment by joshschumacher** [comment]
I think I am seeing this same issue. I'm only seeing 30 repos from my private organization.The repository I'm wanting to see doesn't auto-complete and I can't add it manually when I type in the full name of org/repo_name.

**Comment by joshschumacher** [comment]
Thanks for the latest release with bugfixes. I'm still not able to use the app though because I can't add my repository because it doesn't show up in the auto-completer. If fixing the auto-completer isn't possible, maybe we can just add a repository based on text input instead of it only allowing auto-completed repos to be added.

**Comment by tellnes** [comment]
This is also a showstopper for me.

**Comment by Me1000** [comment]
I'm going to go ahead and close this, the latest update allows you to type the repo name and add it even if its not in the list.
